# Generated by Django 5.0.6 on 2024-06-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_categorie'),
    ]

    operations = [
    ]
