# Generated by Django 5.0.6 on 2024-06-19 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
        ('products', '0002_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='products.product'),
        ),
    ]
